---
# defaults file for roles/patroni
# vim: syntax=yaml tabstop=2 shiftwidth=2

#--- Preinstall
download_dir: 'downloads'

# Astra repositories
astra_se_repo_main: "deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-main/ 1.7_x86-64 main contrib non-free"
astra_se_repo_update: "deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-update/ 1.7_x86-64 main contrib non-free"
astra_se_repo_base: "deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-base/ 1.7_x86-64 main contrib non-free"
astra_se_repo_extended: "deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/ 1.7_x86-64 main contrib non-free"
astra_repo_url: 'deb https://dl.astralinux.ru/astra/stable/2.12_x86-64/repository orel main contrib non-free'
key_server: 'keyserver.ununtu.com'
keyserver: 'hkp://keyserver.ubuntu.com:80'
# Others reoisitories
astra_pg_default_release: 'buster-pgdg'
other_pg_default_release: '{{ ansible_distribution_release }}-pgdg'
pg_default_release: "{{ astra_pg_default_release if ansible_distribution | lower == 'astra linux' else other_pg_default_release }}"
astra_pg_repo_url: 'deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main'
other_pg_repo_url: 'deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main'
pg_repo_url: "{{ astra_pg_repo_url if ansible_distribution | lower == 'astra linux' else other_pg_repo_url }}"
pg_repo_keys:
  - 7FCC7D46ACCC4CF8
astra_mamonsu_repo_url: 'deb https://repo.postgrespro.ru/mamonsu/astra-smolensk/1.7 1.7_x86-64 main'
other_mamonsu_repo_url: 'deb https://repo.postgrespro.ru/mamonsu/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main'
mamonsu_repo_url: "{{ astra_mamonsu_repo_url if ansible_distribution | lower == 'astra linux' else other_mamonsu_repo_url }}"
mamonsu_repo_keys:
  - 7F9AE5A62D2DF0B4
astra_zabbix_repo_url: 'https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bdebian10_all.deb'
other_zabbix_repo_url: 'https://repo.zabbix.com/zabbix/6.0/{{ ansible_distribution|lower }}/pool/main/z/zabbix-release/zabbix-release_6.0-4+{{ ansible_distribution|lower }}{{ ansible_distribution_version }}_all.deb'
zabbix_repo_url: "{{ astra_zabbix_repo_url if ansible_distribution | lower == 'astra linux' else other_zabbix_repo_url }}"
zabbix_package_name: "zabbix-{{ ansible_distribution | lower | regex_search('[a-z0-9]+') }}-{{ ansible_distribution_release }}-{{ ansible_distribution_version }}.deb"
# Environment settings
# WARNING:
# Proxy, domain controllers, timeservers etc. must be created in the same project. If nodes from different projects end up on the same hypervisor, network connectivity is lost.
# Timezone
timezone: '/usr/share/zoneinfo/Europe/Moscow'
localtime: '/etc/localtime'
# Proxy
#proxy_address: '10.169.0.6' # old proxy; don't use
use_proxy: 'true'
proxy_address: '10.169.20.5'
proxy_port: '3128'
proxy: 'http://{{ proxy_address }}:{{ proxy_port }}'
proxy_env:
  http_proxy: '{{ proxy }}'
  https_proxy: '{{ proxy }}'
  HTTP_PROXY: '{{ proxy }}'
  HTTPS_PROXY: '{{ proxy }}'
  
# NTP
ntp1: '10.169.20.3'
ntp2: '10.169.20.4'
ns1: '10.169.20.3'
ns2: '10.169.20.4'
zabbix_server: '10.169.2.3,10.169.2.5'
server_active: '10.169.2.3;10.169.2.5'

# Domain settings
domain: 'inno.local'
domain_nameserver: '10.169.20.3'
computer_ou: 'OU=Servers,OU=Computers,OU=CloudDZO,OU=CENTER,DC=inno,DC=local'
admin_server: 'cd-dc-03.inno.local'
kdc1: 'cd-dc-03.inno.local' 
kdc2: 'cd-dc-04.inno.local'
dc_backup1: 'DC1.inno.local'
dc_backup2: 'DC2.inno.local'
join_user: 'cd-aao-vlika'
join_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30326536316634333065323664333936316234646263373434666361393366346133353934663039
          6435353633303637663661383066356537396139653862630a616433396463326663316361313833
          35356232333665316432336166313366653830613934633862656337633438613635623031663334
          6430653230396636340a613539616161303161333737346539346161616463313364343465306232
          63323236613531653638313762613038663666303964343834376364303034623930
simple_allow_groups: 'cd-admins-db, cd-admins-lnx'
simple_allow_users: 'ib_audit'
