---
# vim: syntax=yaml tabstop=2 shiftwidth=2
# Configure root .bashrc
- name: configure root .bashrc
  copy:
    src: .bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644
    backup: true
...
