---
# vim: syntax=yaml tabstop=2 shiftwidth=2
# Disable Linux firewall
- name: check ufw enabled
  raw: "systemctl is-enabled ufw"
  register: ufw_is_enabled
  ignore_errors: true
  changed_when: false
  tags:
    - preinstall
    - firewall

- name: set fact from output
  set_fact:
    ufw_state: '{{ ufw_is_enabled.stdout }}'
    cacheable: true
  tags:
    - preinstall
    - firewall

- name: disable ufw
  systemd:
    name: ufw
    state: stopped
    enabled: false
    masked: true
  when:
    - ufw_state == 'enabled'
...
