---
# vim: syntax=yaml tabstop=2 shiftwidth=2
# Install essential packages
- name: 'insatall essential packages'
  when: ansible_distribution_release == "1.7_x86-64"
  apt:
    name: '{{ item }}'
    state: present
    default_release: stable
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - chrony
    - cloud-utils
    - curl
    - dnsutils
    - ethtool
    - gdisk
    - gnupg
    - jq
    - libreadline-dev
    - locate
    - net-tools
    - rsync
    - software-properties-common
    - tree
    - tzdata
    - vim
    - wget
  tags: preinstall
...
