---
# tasks file for roles/preinstall
# vim: syntax=yaml tabstop=2 shiftwidth=2
#- name: disable firewall
#  include_tasks: disable_firewall.yml
#  tags: preinstall

- name: configure timezone
  include_tasks: configure_timezone.yml
  tags: preinstall

- name: configure nameservers
  include_tasks: configure_nameservers.yml
  tags: preinstall

- name: configure apt proxy
  include_tasks: configure_apt_proxy.yml
  tags: preinstall

- name: configure astra se repo
  include_tasks: configure_astra_se_repo.yml
  tags: preinstall

- name: install essential packages
  include_tasks: install_essential_packages.yml
  tags: preinstall

- name: configure root bashrc
  include_tasks: configure_root_bashrc.yml
  tags: preinstall

- name: create zabbix local account
  include_tasks: create_zabbix_user.yml
  tags: preinstall
...
