---
# vim: syntax=yaml tabstop=2 shiftwidth=2
# Configure timezone
- name: 'configure timezone'
  file:
    src: '{{ timezone }}'
    dest: '{{ localtime }}'
    state: link
    force: true
  tags: preinstall
...
