---
# vim: syntax=yaml tabstop=2 shiftwidth=2
# Configure apt proxy
- name: 'configure apt proxy'
  lineinfile:
    path: /etc/apt/apt.conf
    line: 'Acquire::http::Proxy "http://{{ proxy_address }}:{{ proxy_port }}";'
    state: present
    create: true
    insertafter: EOF
  when: 
    - ansible_pkg_mgr == 'apt'
    - use_proxy is defined
    - use_proxy == 'true'
...
