---
# vim: syntax=yaml tabstop=2 shiftwidth=2
# Configure nameservers
- name: get internal ns
  tags: 
    - resolvconf
    - preinstall
  set_fact:
    int_ns: "{{ ansible_default_ipv4.network | regex_search('[0-9]+\\.[0-9]+\\.[0-9]+\\.') }}2"

- name: configure astra
  tags: 
    - resolvconf
    - preinstall
  when: ansible_distribution | lower == 'astra linux'
  block:
    - name: drop resolv.conf origin
      file:
        path: /etc/resolv.conf
        state: absent
    - name: create /etc/resolv.conf
      blockinfile:
        path: /etc/resolv.conf
        create: true
        state: present
        owner: root
        group: root
        mode: 0644
        block: |
          nameserver {{ domain_nameserver }}
          nameserver {{ int_ns }}
          domain inno.local
          search inno.local internal

    - name: configure dhclient
      copy:
        dest: /etc/dhcp/dhclient-enter-hooks.d/leave_my_resolv_conf_alone
        force: true
        owner: root
        group: root
        mode: 0755
        content: |
          make_resolv_conf() { :; }

- name: configure ubuntu
  tags: 
    - resolvconf
    - preinstall
  when: ansible_distribution | lower == 'ubuntu'
  block:
    - name: configure nsswitch.conf
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts:'
        line: "hosts:          files resolve dns"
        state: present

    - name: configure /etc/systemd/resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '{{ item.line_expr }}'
        line: '{{ item.line_replace }}'
        state: present
      loop:
        - { line_expr: '^DNS=', line_replace: 'DNS={{ domain_nameserver }} {{ int_ns }}' }
        - { line_expr: '^FallbackDNS=', line_replace: 'FallbackDNS=' }
        - { line_expr: '^Domains=', line_replace: 'Domains=~.{{ domain }}' }

    - name: create symlink
      file:
        src: /run/systemd/resolve/stub-resolv.conf 
        dest: /etc/resolv.conf
        state: link
        force: true
      notify:
        - systemd-resolved enabled

