---
# vim: syntax=yaml tabstop=2 shiftwidth=2
- name: create zabbix local account
  block:
    - name: create group
      group:
        name: zabbix
        state: present
        system: true
    - name: create user
      user:
        name: zabbix
        group: zabbix
        home: /var/lib/zabbix
        shell: /sbin/nologin
        state: present
        system: true
